const CONTEUDO = {
	"funcdomes_yellow": ["Quadro de funcionário do mês", "yellow", "O quadro de funcionário do mês com a foto de Alice, pela primeira vez. Ela parece estar feliz na foto.\n\nTábata: 'Nunca havia me importado em ser funcionária do mês. Parecia algo natural para mim. Mas agora vendo Alice sinto algo que me deixa estranha.'"],
	"enzo_yellow": ["Enzo, colega de trabalho", "yellow", "Enzo: 'E aí Tabatinha! Não te vi no churrasco da empresa!'\n\nTábata: 'Que churrasco?'\n\nEnzo: 'Ihhh. Não te convidaram pra confra da firma? Foi nesse findi. Bebi todas. O pessoal estava muito louco. E tu sabe como eu sou, não perco uma festa!'\n\nTábata: * Eu sinceramente não me importo de não ser convidada pra confraternização da empresa, mas é estranho de qualquer forma *"],
	"mesapcvazio_yellow": ["Mesa de trabalho praticamente vazia", "yellow", "A mesa de Henrique. Está praticamente vazia, se não fosse por um monitor desconectado.\n\nTábata: 'Faz duas semanas que Henrique se demitiu. Nunca falei direito com ele, mas fazia tempo que ele parecia distante e cansado.'"],
	"computador_red": ["Computador de trabalho da Tábata", "red", "O computador que usa todo dia, com várias planilhas abertas e o email com um número cada vez maior de mensagens não respondidas.\n\nTábata: 'Meu computador, aqui é o lugar onde passo a maior parte do tempo. Olhar pra essa tela todos os dias... é algo que tenho que lidar, não tenho outra opção mesmo.'"],
	"seloqualidade_red": ["Selo de qualidade da empresa", "red", "O selo de qualidade da empresa, um símbolo de excelência e orgulho para a chefe.\n\nTábata: 'É, trabalhar em uma das empresas de maior prestígio da cidade não é algo que estava exatamente nos meus planos, mas foi algo que me concedeu estabilidade e uma folga das cobranças dos meus pais.'"],
	"alice_red": ["Alice, colega de trabalho", "red", "Alice é uma das únicas mulheres da empresa junto com Tabata e a Chefe.\n\nTábata: *Alice é uma pessoa boa, alguém que eu poderia me conectar, talvez, mas não há espaço pra isso, e não quero nem pensar em colegas depois da minha última experiência, é melhor deixar só no convívio profissional.*"],
	"chefe_gray": ["Foto de Patricia, chefe da empresa", "gray", "Patricia, e seu nariz empinado... A Chefe da empresa, herdeira, óbvio.\n\nTábata: 'Parece muito simpática e calorosa, mas com o tempo fica claro que ela tem seus preferidos e que sempre se coloca em primeiro lugar.'"],
	"pontoeletronico_gray": ["Ponto eletrônico", "gray", "O ponto eletrônico, portal para a rotina inescapável de uma jornada laboral monótona\n\nTábata: 'É aqui que recomeça o ciclo, a mesma coisa todo dia, bater ponto, le planilha, fazer negócios e conseguir mais clientes para empresa, está longe de ser um trabalho prazeroso...'"],
	"espelho_gray": ["Espelho do banheiro", "gray", "O espelho, testemunha silenciosa do meu estado mental.\n\nTábata: 'Estou exausta, meu rosto está péssimo, ir no banheiro da empresa perceber isso se tornou rotina, o que diabos está acontecendo comigo?'"],
	"cafeteira_blue": ["Cafeteira com defeito", "blue", "A única cafeteira elétrica disponível pra gente, que está quebrada há meses.\n\nTábata: 'A cafeteira quebrada. Como uma repartição pública pode funcionar sem café? Agora temos apenas café instantâneo. Provavelmente nunca irão arrumar essa cafeteira. É sempre assim, algo quebra e nunca é arrumado, só colocam algo pior no lugar.'"],
	"francisco_blue": ["Francisco, colega novo de trabalho", "blue", "Francisco : 'Olá, tudo bem ? Me chamo Francisco, sou o novo estagiário da empresa!'\n\nTábata: 'Ah sim, seja bem-vindo'\n\nFrancisco: 'Se precisar de qualquer ajuda estou a disposição!'\n\nTábata: 'Ele me lembra quando eu era mais jovem, na faculdade de administração, mas ele parece que realmente sabe o que quer, faz um tempo que não sei, ou não me importo o bastante, mas deve ser porque ele é mais jovem, eu acho.'"],
	"placeholder_blue": ["Patricia, chefe da empresa", "blue", "Patricia: 'Ei Tabatinha, não conseguiu ser a colaboradora do mês, né? Fiquei surpresa, mas faz tempo que percebo que está muito “avoada”, um olhar distante, olha lá hein, você tem potencial, espero mais de você, só um feedback, tchau!'\n\nTábata: 'Certo chefe, irei me esforçar mais.'\n\nTábata: *O problema não é esforço, não tem como ser, eu dou tudo de mim, mas eu não me sinto bem, eu recebo prestígio, mas isso não me dá orgulho, eu sei que trabalho não é fácil, mas será que deveria ser tão angustiante?*"],
	"folheto_orange": ["Marmita da Tábata", "orange", "Mais uma marmita elaborada da tabata\n\nTábata: 'Finalmente, melhor momento do dia, hora do almoço, eu sempre me esforço muito com a minha comida, meio que sempre gostei de cozinhar...'\n\nTábata: 'Às vezes até penso que nasci pra isso. Será que faz sentido ? Eu sempre ouvi que fazer comida é hobby, não profissão, mas quando eu tô na cozinha é tão diferente de estar aqui...'"],
	"poster_orange": ["Poster sobre pacote de viagem", "orange", "Um poster sobre um pacote de viagens da agência que a empresa tem parceria.\n\nTábata: 'Talvez eu precise viajar, só isso, viajar pra qualquer lugar, fingir que nada disso existe e que minha vida é perfeita, e depois volto a rotina...'"],
	"pilhapapeis_orange": ["Pilha de trabalho para Tábata", "orange", "Pilha de papéis, mais trabalho, mais dedicação, mais resultados\n\nTábata: 'Vamos lá de novo, pelo menos pra isso aqui eu já tô acostumada, eu sirvo pra algo, eu faço o que eles pedem e eles me deixam em paz, assim, eu vou seguindo.'"]
}
