extends Node

var is_chatting = false
var is_dragging = false
var is_correct = false
var is_wrong = false
var all_in = false
var segue = false
var primeiro = true 
var cuts = false
var restart = false
var alternat = false
var cena_atual = preload("res://cenas/ep_1/cenario1.tscn")
var carta_atual
var hand_full = false
var hand = []
var classe_hand = []
var classe_atual 
var gabinete = false
var apertou = false
var novo = false
var mostra = ""
var marmita = false
var first_turorial = true
var paused = false
var texto_psico = false
var primeiro_gabinete = true
func reiniciar():
	Globals.restart = true
	GabinetePensamento.slots_salvos = {}  # Exemplo: {0: "carta1", 1: "carta2"}
	GabinetePensamento.itens_coletados = []
	GabinetePensamento.player_hand = []
	GabinetePensamento.mao_string = []
	GabinetePensamento.slots_certos = 0
	Globals.cuts = false
	Globals.segue = false
	GabinetePensamento.avanco = false
	NavigationManager.spawn_door_tag = null
	Globals.is_chatting = false
	Globals.gabinete = false
	Globals.paused = false
	Globals.marmita = false
	DialogoTracker.primeiraescolha = ""
	DialogoTracker.segundaescolha = ""
	DialogoTracker.terceiraescolha = ""
	DialogoTracker.quartaescolha = ""
	DialogoTracker.textofinal = ""
	DialogoTracker.juntetextos = false
	DialogoTracker.quintaescolha = ""
	DialogoTracker.sextaescolha = ""
	DialogoTracker.setimaescolha = ""
	DialogoTracker.oitavaescolha = ""
	DialogoTracker.nonaescolha = ""
	DialogoTracker.decimaescolha = ""
	DialogoTracker.decimaprimeiraescolha = ""
	DialogoTracker.decimasegundaescolha = ""
	DialogoTracker.decimaterceiraescolha = ""
	DialogoTracker.prim_1 = false
	DialogoTracker.prim_2 = false
	DialogoTracker.prim_3 = false
	DialogoTracker.seg_1 = false
	DialogoTracker.seg_2 = false
	DialogoTracker.seg_3 = false
	DialogoTracker.tri_1 = false
	DialogoTracker.tri_2 = false
	DialogoTracker.tri_3 = false
